### ISSUE TITLE
如果你能用白色，我认输

### ISSUE THREAD

**Issue by JakeRed** [koudle/AndroidSiriWave#1]
我也是用ADD模式画波形图，但是背景是白色的时候基本就不可以用了，没找到好的解决方案

**Comment by koudle** [comment]
我周末试一下

**Comment by koudle** [comment]
是因为做渐变效果的时候用到了白色，所以背景是白色的时候效果就不好，但是如果做渐变效果不用白色就好了

**Comment by JakeRed** [comment]
渐变的颜色改变也是不可以的，ADD模式的情况下做的渐变paint画图是要取背景色参与渲染的缘故吧，不可能实现白底情况下的深色前景色，该问题存在并且不容易fixed，不应该close。

**Comment by koudle** [comment]
有道理
